### ISSUE TITLE
Mounting Local Files Using “Mount Local Folder” Function

### ISSUE THREAD

**Issue by bolenala** [sandbox-bio/sandbox.bio#100]
I encountered an issue while attempting to mount local files in different folders using the “mount local folder” function. When I select a folder with subfolders, all the content gets uploaded into the tutorial folder without preserving the original folder structure. Ideally, I’d like the files to be uploaded with the same folder structure as on my local machine. This is the case for Firefox, Chrome and Edge browsers.

**Comment by robertaboukhalil** [comment]
@bolenala Great idea, thanks! I've merged a fix now and it will be deployed tomorrow
