### ISSUE TITLE
Use `cd` without argument

### ISSUE THREAD

**Issue by thomasdenecker** [sandbox-bio/sandbox.bio#19]
**How to reproduce the issue?**

When the command `cd` without argument is issued in the linux terminal, the response is 

```
guest@sandbox$ cd
undefined: No such file or directory
````
instead of returning to home.

**Suggested solution**

In the `app/src/terminal/cli.js` file

```
[...]
cd: async args => {
		let dir = args._[0];
		// Support cd ~ and cd -
		if (dir === undefined)
			dir = "/shared/home/";
		else if (dir == "~")
			dir = $env.HOME;
		else if (dir == "-" && _wd)
			dir = _wd;
		// Change directory
		const dirOld = await coreutils.pwd();
		try {
			await _aioli.cd(dir);
			_wd = dirOld;
		} catch (error) {
			return `${dir}: No such file or directory`;
		}
		return "";
	},
[...]
```

Many thanks in advance!

**Comment by robertaboukhalil** [comment]
Nice, thanks @thomasdenecker! Feel free to send a PR if you want credit for the change. I'm also happy to do it if not.
